'''
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''

generatedNumber = 1038


def getInput():
  global playerNumber
  playerNumber = input('Type your number: ')
  return playerNumber

def CowsAndBulls():
  global Cows
  global Bulls2
  genNumList = [int(i) for i in str(generatedNumber)]
  playerNumList = [int(i) for i in str(playerNumber)]
  Cows = sum([True for i in playerNumList if i in genNumList])
  Bulls1 = [[i in genNumList for i in genNumList if i==j] for j in playerNumList]
  Bulls2 = sum([not(not i) for i in Bulls1])
  print('Cows: ' + str(Cows) + ', Bulls: ' + str(Bulls2) + '\n')
  return Cows
  return Bulls2
 

def Game():
  getInput()
  CowsAndBulls()
  if int(Cows) == 4:
    print('Win!')
  else:
    print(':(')
    Game()
  

print('Guess 4 digit randomly generated number.')
Game()
